# Generated by Django 3.2.5 on 2021-07-22 14:01


from django.db import migrations, models
from recipe.models import TimeStampMixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('unit_type', models.CharField(choices=[('solid', 'Solid'), (
                    'liquid', 'Liquid'), ('solid_and_liquid', 'Solid and Liquid')], max_length=32)),
                ('multiplier', models.FloatField(null=True)),
                ('symbol', models.CharField(max_length=16)),
            ],
            bases=(models.Model, TimeStampMixin),
        ),
    ]
