# Generated by Django 3.2.5 on 2021-07-22 14:01


from django.db import migrations, models
from recipe.models import TimeStampMixin, Unit


def create_units(apps, schema_editor):
    """Creates the base units."""

    units = [
        {
            'name': 'Kilogram',
            'unit_type': Unit.unit_choices[2][0],
            'multiplier': 1000.0,
            'symbol': 'kg'
        },
        {
            'name': 'Gram',
            'unit_type': Unit.unit_choices[2][0],
            'multiplier': 1.0,
            'symbol': 'g'
        },
        {
            'name': 'Liter',
            'unit_type': Unit.unit_choices[1][0],
            'multiplier': 1.0,
            'symbol': 'l'
        },
        {
            'name': 'Centiliter',
            'unit_type': Unit.unit_choices[1][0],
            'multiplier': 100.0,
            'symbol': 'cl'
        },
    ]

    for unit in units:
        Unit.objects.create(**unit)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('unit_type', models.CharField(choices=[('solid', 'Solid'), (
                    'liquid', 'Liquid'), ('solid_and_liquid', 'Solid and Liquid')], max_length=32)),
                ('multiplier', models.FloatField(null=True)),
                ('symbol', models.CharField(max_length=16)),
            ],
            bases=(models.Model, TimeStampMixin),
        ),
        migrations.RunPython(create_units),
    ]
