# Generated by Django 3.2.5 on 2021-07-22 17:36

from django.db import migrations, models
from recipe.models import Unit


def create_units(apps, schema_editor):
    """Creates the base units."""

    units = [
        {
            'name': 'Kilogram',
            'unit_type': Unit.unit_choices[2][0],
            'multiplier': 1.0,
            'symbol': 'kg'
        },
        {
            'name': 'Gram',
            'unit_type': Unit.unit_choices[2][0],
            'multiplier': 1000.0,
            'symbol': 'g',
            'is_default': True,
        },
        {
            'name': 'Liter',
            'unit_type': Unit.unit_choices[1][0],
            'multiplier': 1.0,
            'symbol': 'l'
        },
        {
            'name': 'Centiliter',
            'unit_type': Unit.unit_choices[1][0],
            'multiplier': 100.0,
            'symbol': 'cl',
            'is_default': True,
        },
    ]

    for unit in units:
        Unit.objects.create(**unit)


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_default',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.RunPython(create_units),
    ]
