# Generated by Django 3.2.5 on 2021-07-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_recipeingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'verbose_name_plural': 'Recipe Ingredients'},
        ),
    ]
