# Generated by Django 3.2.5 on 2021-07-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20210722_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='price_per_unit_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
