version: '3.9'

services:
  db:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: recipe_box
      MYSQL_ROOT_PASSWORD: bloodyroots

  web:
    build: .
    command: bash -c "sleep 15s
      && python manage.py collectstatic --noinput
      && python manage.py migrate
      && python manage.py loaddata seed_data.json
      && gunicorn recipe_box.wsgi"
    environment:
      DJANGO_SUPERUSER_PASSWORD: 123456
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    volumes:
      - .:/code
    ports:
      - '8080:8080'
    depends_on:
      - db
